blank_issues_enabled: false
contact_links:
  - name: Bug Reports (and other issues)
    url: https://github.com/pradyunsg/furo/discussions/categories/potential-issue
    about: Possible bugs may be raised as a "Potential Issue" discussion.
  - name: Feature Request / Enhancement
    url: https://github.com/pradyunsg/furo/discussions/categories/ideas
    about: Feature requests may be raised as an "Ideas" discussion.
  - name: Express Gratitude
    url: https://shoutouts.dev/projects/pradyunsg/furo
    about: You like the project, and would like to tell @pradyunsg that! :)
